// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzajOpS4mrZfVdj2wGgt5Oc2VbYoJcLk',
    appId: '1:1012255979587:web:b8960e2da2d44d546fbcf6',
    messagingSenderId: '1012255979587',
    projectId: 'uber-eats-clone-1f233',
    authDomain: 'uber-eats-clone-1f233.firebaseapp.com',
    storageBucket: 'uber-eats-clone-1f233.appspot.com',
    measurementId: 'G-26W9SB8M84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBSWRmEmIDTuBjEru0MLv3uwMdSarQvP0',
    appId: '1:1012255979587:android:4a100378d0c740776fbcf6',
    messagingSenderId: '1012255979587',
    projectId: 'uber-eats-clone-1f233',
    storageBucket: 'uber-eats-clone-1f233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2oEXv0Nk5dO5xN_uu9XkFBcK2wKMNnA8',
    appId: '1:1012255979587:ios:fc890d34dd71ebc06fbcf6',
    messagingSenderId: '1012255979587',
    projectId: 'uber-eats-clone-1f233',
    storageBucket: 'uber-eats-clone-1f233.appspot.com',
    iosBundleId: 'com.example.uberEatsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2oEXv0Nk5dO5xN_uu9XkFBcK2wKMNnA8',
    appId: '1:1012255979587:ios:fc890d34dd71ebc06fbcf6',
    messagingSenderId: '1012255979587',
    projectId: 'uber-eats-clone-1f233',
    storageBucket: 'uber-eats-clone-1f233.appspot.com',
    iosBundleId: 'com.example.uberEatsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXzajOpS4mrZfVdj2wGgt5Oc2VbYoJcLk',
    appId: '1:1012255979587:web:1d2a3853d0a85ce56fbcf6',
    messagingSenderId: '1012255979587',
    projectId: 'uber-eats-clone-1f233',
    authDomain: 'uber-eats-clone-1f233.firebaseapp.com',
    storageBucket: 'uber-eats-clone-1f233.appspot.com',
    measurementId: 'G-3JW65PEXSB',
  );
}
